language: java

sudo: false # faster builds

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - MAVEN_OPTS="-Xmx4g"
    - JAVA_OPTS="-Xmx4g"

jdk:
 - oraclejdk8

before_install:
 - chmod +x ./mvnw

script:
  - mvn clean verify -Denv=dev -Pdebug,dep-jacoco,enforcer

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: maxur:bIyYFLYJ0n1toR66dIr5OSbD